baseURL = 'https://razvanm.github.io/vanadium-website/'
languageCode = 'en-us'
title = 'Vanadium'
theme = 'vanadium'
canonifyURLs = true

# We disable some kinds to make it possible to serve certain pages instead of
# the index pages.
disableKinds = ['section', 'taxonomy']
ignoreErrors = ['error-disable-taxonomy']

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
  startLevel = 1
  endLevel = 3
  ordered = false
