baseURL = 'https://razvanm.github.io/vanadium-website/'
languageCode = 'en-us'
title = 'Vanadium'
theme = 'vanadium'
canonifyURLs = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
  startLevel = 1
  endLevel = 3
  ordered = false
